name: Publish to NPM

on:
  release:
    types: [published]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn install

      - name: Determine NPM Tag
        id: determine-npm-tag
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/v}
          if [[ $VERSION_TAG == *"-rc"* ]]; then
            echo "NPM_TAG=next" >> $GITHUB_OUTPUT
          else
            echo "NPM_TAG=latest" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Update config.json version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          jq --arg v "$VERSION" '.version = $v' src/config.json > tmp.json && mv tmp.json src/config.json
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Build
        run: yarn build && cat dist/config.json

      # - name: Publish to NPM
      #   run: yarn publish --new-version ${GITHUB_REF#refs/tags/v} --tag ${{ steps.determine-npm-tag.outputs.NPM_TAG }} --no-git-tag-version
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_REF: ${{ github.ref }}

      # - name: Also tag as `next` if tag is `latest`
      #   if: steps.determine-npm-tag.outputs.NPM_TAG == 'latest'
      #   run: |
      #     VERSION=${GITHUB_REF#refs/tags/v}
      #     npm dist-tag add zetachain@$VERSION next
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
