name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn install

      - name: Determine NPM Tag and Version
        id: determine-npm-tag
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/v}
          if [[ $VERSION_TAG == *"-"* ]]; then
            echo ::set-output name=NPM_TAG::${VERSION_TAG#*-}
          else
            echo ::set-output name=NPM_TAG::latest
          fi
          echo ::set-output name=VERSION::${VERSION_TAG}
        env:
          GITHUB_REF: ${{ github.ref }}

      - name: Build
        run: yarn build
        env:
          ZETACHAIN_CLI_VERSION: ${{ steps.determine-npm-tag.outputs.VERSION }}

      - name: Publish to NPM
        run: yarn publish --new-version ${{ steps.determine-npm-tag.outputs.VERSION }} --tag ${{ steps.determine-npm-tag.outputs.NPM_TAG }} --no-git-tag-version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_REF: ${{ github.ref }}
